spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/liquibase_example
    username: eertree
    driver-class-name: org.postgresql.Driver
    password: password
    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.xml